Enabled: true
Ban-Time: 1d2h34m
Death-Message: Sorry, you have died and are now banned until %unbantime% on %unbandate%.
Banned-Message: Sorry, your ban is not up until %unbantime% on %unbandate%.
Tick-Delay: 15
Verbose: false